function handles=init_figure_600x330(figure_property)
% Written by Jia Xi-ze 150720.
% figure_property.figure_name;
%-----------------------------------------------------------
%   Copyright(c) 2015
%	Center for Cognition and Brain Disorders, Hangzhou Normal University, Hangzhou 310015, China
%	Written by JIA Xi-Ze 201507
%	http://www.restfmri.net/
% 	Mail to Authors: jxz.rest@gmail.com, jiaxize@foxmail.com

handles.h_fig =figure('Units', 'pixel',...
                  'Toolbar', 'none',...
                  'MenuBar', 'none', ...
			      'NumberTitle', 'off',...
                  'Visible', 'off', ...					
			      'Name', figure_property.figure_name, ...
			      'Position', [0,0,600, 330],...
                  'Resize','off',...
                  'Color', [240/250,240/250,240/250]);                               
movegui(handles.h_fig, 'center');  
end